### ISSUE TITLE
Slack notification is not working

### ISSUE THREAD

**Issue by aldochristiansense** [duck8823/danger-slack#8]
I'm trying using danger-slack to notify my team ..
But it doesn't work ..
I tried using `slack.api_token` inside Dangerfile and set env variable `SLACK_API_TOKEN` on Travis ..
Is there any step that i missed ?

**Comment by duck8823** [comment]
Thanks for trying use this plugin.
Perhaps you forgot to invite bot in your channel ?

**Comment by aldochristiansense** [comment]
hmm , i didn't remember there is a step to invite bot to our channel ? 😕 
oh yes, by the way my project language is : objective-c

**Comment by duck8823** [comment]
Sorry, I don't written to README slack settings step.

The following steps is required for using danger-slack plugin.
1. create bot in https://my.slack.com/services/new/bot
2. invite created bot user to channel in slack app

`slack.api_token` or `SLACK_API_TOKEN` are the bot's token starting from `xoxb-`

If you are doing as described above, I need more detail for solve problem.
Can I see any log or your dangerfile.

**Comment by aldochristiansense** [comment]
Oops, i haven't done this yet. Let me try it first and report later 👍

**Comment by aldochristiansense** [comment]
Hello, i got this when using it inside Dangerfile:

```
html_url = github.pr_json["html_url"]		
￼slack.notify(channel: "#x_ios_sdk", text: "Hello, PR has been checked using danger. Please go to : #{html_url} , Thank You! ")
```

Got this error 😕 

```
bundle exec danger | tee danger.log
bundler: failed to load command: danger (/Users/travis/build/senseobservationsystems/iris-ios/vendor/bundle/ruby/2.4.0/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: undefined local variable or method `￼slack' for #<Danger::Dangerfile:0x007f8cda2bd590>
Did you mean?  slack
               @slack
 #  from Dangerfile:36
 #  -------------------------------------------
 #  html_url = github.pr_json["html_url"]		
 >  ￼slack.notify(channel: "#x_ios_sdk", text: "Hello, PR has been checked using danger. Please go to : #{html_url} , Thank You! ")
 #  -------------------------------------------
  /Users/travis/build/senseobservationsystems/iris-ios/vendor/bundle/ruby/2.4.0/gems/danger-5.4.0/lib/danger/danger_core/dangerfile.rb:68:in `method_missing'
  Dangerfile:36:in `block in parse'
  /Users/travis/build/senseobservationsystems/iris-ios/vendor/bundle/ruby/2.4.0/gems/danger-5.4.0/lib/danger/danger_core/dangerfile.rb:199:in `eval'
  /Users/travis/build/senseobservationsystems/iris-ios/vendor/bundle/ruby/2.4.0/gems/danger-5.4.0/lib/danger/danger_core/dangerfile.rb:199:in `block in parse'
  /Users/travis/build/senseobservationsystems/iris-ios/vendor/bundle/ruby/2.4.0/gems/danger-5.4.0/lib/danger/danger_core/dangerfile.rb:195:in `instance_eval'
  /Users/travis/build/senseobservationsystems/iris-ios/vendor/bundle/ruby/2.4.0/gems/danger-5.4.0/lib/danger/danger_core/dangerfile.rb:195:in `parse'
  /Users/travis/build/senseobservationsystems/iris-ios/vendor/bundle/ruby/2.4.0/gems/danger-5.4.0/lib/danger/danger_core/dangerfile.rb:272:in `run'
  /Users/travis/build/senseobservationsystems/iris-ios/vendor/bundle/ruby/2.4.0/gems/danger-5.4.0/lib/danger/danger_core/executor.rb:27:in `run'
  /Users/travis/build/senseobservationsystems/iris-ios/vendor/bundle/ruby/2.4.0/gems/danger-5.4.0/lib/danger/commands/runner.rb:66:in `run'
  /Users/travis/build/senseobservationsystems/iris-ios/vendor/bundle/ruby/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/travis/build/senseobservationsystems/iris-ios/vendor/bundle/ruby/2.4.0/gems/danger-5.4.0/bin/danger:5:in `<top (required)>'
  /Users/travis/build/senseobservationsystems/iris-ios/vendor/bundle/ruby/2.4.0/bin/danger:23:in `load'
  /Users/travis/build/senseobservationsystems/iris-ios/vendor/bundle/ruby/2.4.0/bin/danger:23:in `<top (required)>'
```

**Comment by duck8823** [comment]
humm... 
it seems that danger don't recognize slack plugin. 
Did you add `gem 'danger-slack'` in your Gemfile and bundle install ?

**Comment by aldochristiansense** [comment]
![screen shot 2017-09-07 at 4 26 32 pm](https://user-images.githubusercontent.com/17135819/30156308-867d9ec4-93e9-11e7-970f-e74354a8913d.png)
![screen shot 2017-09-07 at 4 26 46 pm](https://user-images.githubusercontent.com/17135819/30156314-88a91318-93e9-11e7-88fb-f9f34aab0f34.png)

Yes, i added it on my `Gemfile` and also add `Gemfile.lock` ..

Run `bundle install`

![screen shot 2017-09-07 at 4 30 02 pm](https://user-images.githubusercontent.com/17135819/30156420-d441207c-93e9-11e7-8c59-ff02a9fb2e6e.png)

**Comment by duck8823** [comment]
Thanks and It's looks good...

I tried this plugin in travis and succeed.
https://github.com/duck8823/danger-slack/pull/9
https://travis-ci.org/duck8823/danger-slack/jobs/272835653

This is my .travis.yml that will probably help you. 
https://github.com/duck8823/danger-slack/blob/master/.travis.yml

I have encountered a similar error before.
At that time, I ran danger in fastlane without use_bundle_exec option.
Threfore, The following command was assembled
`bundle exec bundle exec danger`

**Comment by aldochristiansense** [comment]
It looks like i have typo in my dangerfile ..
I got this information from travis support , they saw this unicode character `ï¿¼` inside my dangerfile which is invisible in my visual studio code IDE .. lul :(

```
html_url = github.pr_json["html_url"]		
 >  ï¿¼slack.notify(channel: '#x_ios_sdk', text: 'Hello, PR has been checked using danger. Please go to : #{html_url} , Thank You! ')
```

Will let you know after my travis build finish, because right now travis have some problem with their OSX build 😖

**Comment by duck8823** [comment]
I see. 😀
I hope your  travis build to be success.

**Comment by aldochristiansense** [comment]
Hello thank you for you support and help, now the notification works!
It will be good if you add step for creating a bot just like you said above 👍 
I will close this issue 🎉
